branches: [ dev, qa, master]
event: pull_request
pipeline:
  clone:
    image: plugins/git
    commands:
      - git config --global user.email "drone-bot@moengage.com"
      - git config --global user.name "Drone CI"
      - git init
      - git remote add origin https://github.com/moengage/ci-test.git
      - sleep 5
      - git fetch --no-tags origin pull/$DRONE_PULL_REQUEST/merge
  install:
    image: node:8.1.2
    commands:
      - npm install --global yarn
      - yarn install
  test:
    image: node:8.1.2
    commands:
      - yarn test
  # integration-test:
  #   image: node:8.1.2
  #   when:
  #     branch: [ dev ]
  #     event: pull_request
  #   commands:
  #     - git branch -D merged_state || true
  #     - git fetch origin pull/$CI_PULL_REQUEST/head:merged_state
  #     - git fetch origin $DRONE_BRANCH
  #     - git checkout $DRONE_BRANCH
  #     - git pull origin $DRONE_BRANCH
  #     - git merge --no-ff merged_state
  #     - git log -2
  #     - yarn test
  notify-build-status:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
    template: >
      {{#success build.status}}
        {{repo.name}} ({{build.branch}}) <{{ build.link }}|{{ repo.owner }}/{{ repo.name }}#{{truncate build.commit 8}}> build succeeded on {{uppercasefirst build.event}}. Good job {{ build.author }}.
      {{else}}
        {{repo.name}} ({{build.branch}}) <{{ build.link }}|{{ repo.owner }}/{{ repo.name }}#{{truncate build.commit 8}}> build failed on {{uppercasefirst build.event}}. Fix me please {{ build.author }}.
      {{/success}}
