branches: [ dev, qa, master ]
pipeline:
  install:
    image: node:8.1.2
    commands:
      - npm install --global yarn
      - yarn install
  unit-test:
    image: node:8.1.2
    commands:
      - yarn test
  prepare-integration-test:
    image: plugins/git
    commands:
      - git config --global user.email "drone-bot@moengage.com"
      - git config --global user.name "Drone CI"
      - git branch -D merged_state || true
      - git fetch origin pull/$CI_PULL_REQUEST/head:merged_state
      - git fetch origin $DRONE_BRANCH
      - git checkout $DRONE_BRANCH
      - git pull origin $DRONE_BRANCH
      - git merge --no-ff merged_state
      - git log -2
  start-integration-test:
    image: node:8.1.2
    commands:
      - yarn test
  check-dev-file:
    image: node:8.1.2
    commands:
      - cat dev-only_file
  notify:
    image: plugins/slack    
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
    template: >
      {{#success build.status}}
        {{repo.name}} ({{build.branch}}) <{{ build.link }}|{{ repo.owner }}/{{ repo.name }}#{{truncate build.commit 8}}> build succeeded on {{uppercasefirst build.event}}. Good job {{ build.author }}.
      {{else}}
        {{repo.name}} ({{build.branch}}) <{{ build.link }}|{{ repo.owner }}/{{ repo.name }}#{{truncate build.commit 8}}> build failed on {{uppercasefirst build.event}}. Fix me please {{ build.author }}.
      {{/success}}